### ISSUE TITLE
Quest rewards

### ISSUE THREAD

**Issue by Sabben11** [Auctionator/Journalator#51]
Journalator does not seem to include monetary quest rewards that are included in a bag that must be opened. For example, the reward for doing a dragon riding race world quest. It shows that you did the quest under the quest tab but shows the value as 0. Thanks for your effort it is a useful addon.

**Comment by plusmouse** [comment]
The gold should be included on the Looting tab - as that's where gold from containers is currently tracked

**Comment by plusmouse** [comment]
I've found that Journalator didn't track the bag money rewards in the Looting tab either.

This version includes changes so that it will track them too in the Looting tab:
[Journalator-1.31-6-g0edf3f6.zip](https://github.com/Auctionator/Journalator/files/11186470/Journalator-1.31-6-g0edf3f6.zip)

![image](https://user-images.githubusercontent.com/60280559/230800152-87759eb4-5709-4144-b4f3-bf618fa07f52.png)

**Comment by plusmouse** [comment]
Going to close this issue as resolved. No further comments and the gold is now tracked in the Loot -> By Source tab.
